function [fitresult] = trailing(x, trail)
%CREATEFIT(X,TRAIL)
%  Create a fit.
%
%  Data for 'trailing' fit:
%      X Input : x
%      Y Output: trail
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-May-2021 13:31:34


%% Fit: 'trailing'.
[xData, yData] = prepareCurveData( x, trail );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.999580767726325;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
% 
% % Plot fit with data.
% figure( 'Name', 'trailing' );
% h = plot( fitresult, xData, yData );
% % Label axes
% grid on
% hold on 
% ylim([-0.5 1.5])
% xlim([1 3.5])
% ylabel('Cf/Cd')
% xlabel('R/D')
